apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-2
  namespace: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: service-2
    namespace: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  namespace: api
spec:
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      serviceAccount: service-2
      containers:
        - name: api
          image: primozh/k8s-sa-volume-demo-service-2
          env:
            - name: PORT
              value: ":8081"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service-2
  namespace: api
spec:
  selector:
    app: service-2
  ports:
    - port: 8081
      targetPort: 8081
