apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccount: api
      volumes:
        - name: api-token
          projected:
            sources:
              - serviceAccountToken:
                  path: api-token
                  expirationSeconds: 600
                  audience: service-2
      containers:
        - name: api
          image: primozh/k8s-sa-volume-demo-api
          env:
            - name: PORT
              value: ":8080"
            - name: SERVICE_2_CONNECTION_STRING
              value: http://service-2:8081
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/run/secrets/tokens
              name: api-token
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
